# Generated by Django 2.0.5 on 2018-05-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minerals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mineral',
            name='group',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
